# Generated by Django 5.2.8 on 2025-11-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertsettings',
            options={'ordering': ['-created_at']},
        ),
    ]
